# Pandas Practice Notebook

This notebook covers essential Pandas concepts with explanations, definitions, and runnable code examples.

---

## 1. Importing Pandas

**What:** Pandas is a Python library for data manipulation and analysis.

**Why:** It provides powerful data structures like DataFrame and Series.

**How:** Import using `import pandas as pd`.

**When:** Whenever you need to work with tabular data.

In [120]:
import pandas as pd

## 2. Loading Data

**What:** Reading data from CSV files into a DataFrame.

**How:** Use `pd.read_csv()`.

**Where:** Useful for data stored in files.

In [121]:
df = pd.read_csv('raw_data.csv')
df

,user_id,order_id,order_date,order_amount,payment_mode,city
0,1.0,1.000000e+09,2022-01-21 06:27:29,71.65,NaN,Los Angeles
1,2.0,1.000000e+09,2023-03-01 13:01:21,NaN,Cash,NaN
2,3.0,1.000000e+09,2024-03-21 15:37:04,41.49,NaN,Houston
3,4.0,NaN,2020-10-31 09:59:47,39.34,Mobile Payment,Chicago
4,NaN,1.000000e+09,2020-12-10 00:59:59,NaN,Debit Card,Houston
...,...,...,...,...,...,...
499995,499996.0,1.000500e+09,2020-09-24 22:14:19,55.76,Mobile Payment,Los Angeles
499996,499997.0,1.000500e+09,2020-02-20 14:19:47,98.90,Debit Card,Houston
499997,499998.0,1.000500e+09,2021-09-18 00:46:54,16.58,Debit Card,San Francisco
499998,499999.0,1.000500e+09,2022-10-17 07:23:27,60.74,Cash,Seattle
499999,500000.0,1.000500e+09,2024-03-27 23:39:07,40.34,Mobile Payment,New York

## 3. Inspecting Data

**What:** Understanding structure and summary of data.

- `head()` shows first rows
- `tail()` shows last rows
- `info()` gives column types
- `describe()` gives statistics

In [122]:
df.head(10)
df.tail(10)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   user_id       499999 non-null  float64
 1   order_id      499999 non-null  float64
 2   order_date    500000 non-null  object
 3   order_amount  499998 non-null  float64
 4   payment_mode  499998 non-null  object
 5   city          499998 non-null  object
dtypes: float64(3), object(3)
memory usage: 22.9+ MB

In [123]:
df.describe()

             user_id      order_id   order_amount
count  499999.000000  4.999990e+05  499998.000000
mean   250000.999992  1.000250e+09      52.465320
std    144337.422974  1.443374e+05      27.409684
min         1.000000  1.000000e+09       5.000000
25%    125001.500000  1.000125e+09      28.780000
50%    250001.000000  1.000250e+09      52.400000
75%    375000.500000  1.000375e+09      76.180000
max    500000.000000  1.000500e+09     100.000000

## 4. Selecting Columns

**What:** Extract specific columns.

**How:** Use double brackets.

In [124]:
df[['order_amount','payment_mode']]

        order_amount    payment_mode
0              71.65             NaN
1                NaN            Cash
2              41.49             NaN
3              39.34  Mobile Payment
4                NaN      Debit Card
...              ...             ...
499995         55.76  Mobile Payment
499996         98.90      Debit Card
499997         16.58      Debit Card
499998         60.74            Cash
499999         40.34  Mobile Payment

[500000 rows x 2 columns]

## 5. Filtering Data

**What:** Select rows based on conditions.

**How:** Boolean indexing.

In [125]:
condition = df[(df['order_amount'] > 20) & (df['payment_mode'] == 'Cash')]
len(condition)

105702

## 6. Adding Columns

**What:** Create new columns.

**How:** Assign lists or use `insert()`.

In [126]:
df['new_data'] = [i + 2 for i in range(len(df))]
df

,user_id,order_id,order_date,order_amount,payment_mode,city,new_data
0,1.0,1.000000e+09,2022-01-21 06:27:29,71.65,NaN,Los Angeles,2
1,2.0,1.000000e+09,2023-03-01 13:01:21,NaN,Cash,NaN,3
2,3.0,1.000000e+09,2024-03-21 15:37:04,41.49,NaN,Houston,4
3,4.0,NaN,2020-10-31 09:59:47,39.34,Mobile Payment,Chicago,5
4,NaN,1.000000e+09,2020-12-10 00:59:59,NaN,Debit Card,Houston,6
...,...,...,...,...,...,...,...
499995,499996.0,1.000500e+09,2020-09-24 22:14:19,55.76,Mobile Payment,Los Angeles,499997
499996,499997.0,1.000500e+09,2020-02-20 14:19:47,98.90,Debit Card,Houston,499998
499997,499998.0,1.000500e+09,2021-09-18 00:46:54,16.58,Debit Card,San Francisco,499999
499998,499999.0,1.000500e+09,2022-10-17 07:23:27,60.74,Cash,Seattle,500000
499999,500000.0,1.000500e+09,2024-03-27 23:39:07,40.34,Mobile Payment,New York,500001

In [127]:
data = [i + 3 for i in range(len(df))]
df.insert(2,'new_data_2',data)
df

,user_id,order_id,new_data_2,order_date,order_amount,payment_mode,city,new_data
0,1.0,1.000000e+09,3,2022-01-21 06:27:29,71.65,NaN,Los Angeles,2
1,2.0,1.000000e+09,4,2023-03-01 13:01:21,NaN,Cash,NaN,3
2,3.0,1.000000e+09,5,2024-03-21 15:37:04,41.49,NaN,Houston,4
3,4.0,NaN,6,2020-10-31 09:59:47,39.34,Mobile Payment,Chicago,5
4,NaN,1.000000e+09,7,2020-12-10 00:59:59,NaN,Debit Card,Houston,6
...,...,...,...,...,...,...,...,...
499995,499996.0,1.000500e+09,499998,2020-09-24 22:14:19,55.76,Mobile Payment,Los Angeles,499997
499996,499997.0,1.000500e+09,499999,2020-02-20 14:19:47,98.90,Debit Card,Houston,499998
499997,499998.0,1.000500e+09,500000,2021-09-18 00:46:54,16.58,Debit Card,San Francisco,499999
499998,499999.0,1.000500e+09,500001,2022-10-17 07:23:27,60.74,Cash,Seattle,500000
499999,500000.0,1.000500e+09,500002,2024-03-27 23:39:07,40.34,Mobile Payment,New York,500001

## 7. Updating Values

**What:** Modify specific cell values.

**How:** Use `.loc[row, col]`.

In [128]:
df.loc[0,'payment_mode'] = 'Cash'
df

,user_id,order_id,new_data_2,order_date,order_amount,payment_mode,city,new_data
0,1.0,1.000000e+09,3,2022-01-21 06:27:29,71.65,Cash,Los Angeles,2
1,2.0,1.000000e+09,4,2023-03-01 13:01:21,NaN,Cash,NaN,3
2,3.0,1.000000e+09,5,2024-03-21 15:37:04,41.49,NaN,Houston,4
3,4.0,NaN,6,2020-10-31 09:59:47,39.34,Mobile Payment,Chicago,5
4,NaN,1.000000e+09,7,2020-12-10 00:59:59,NaN,Debit Card,Houston,6
...,...,...,...,...,...,...,...,...
499995,499996.0,1.000500e+09,499998,2020-09-24 22:14:19,55.76,Mobile Payment,Los Angeles,499997
499996,499997.0,1.000500e+09,499999,2020-02-20 14:19:47,98.90,Debit Card,Houston,499998
499997,499998.0,1.000500e+09,500000,2021-09-18 00:46:54,16.58,Debit Card,San Francisco,499999
499998,499999.0,1.000500e+09,500001,2022-10-17 07:23:27,60.74,Cash,Seattle,500000
499999,500000.0,1.000500e+09,500002,2024-03-27 23:39:07,40.34,Mobile Payment,New York,500001

## 8. Removing Columns

**What:** Delete unwanted columns.

**How:** Use `drop()`.

In [129]:
df.drop(columns=['new_data_2'], inplace=True)
df

,user_id,order_id,order_date,order_amount,payment_mode,city,new_data
0,1.0,1.000000e+09,2022-01-21 06:27:29,71.65,Cash,Los Angeles,2
1,2.0,1.000000e+09,2023-03-01 13:01:21,NaN,Cash,NaN,3
2,3.0,1.000000e+09,2024-03-21 15:37:04,41.49,NaN,Houston,4
3,4.0,NaN,2020-10-31 09:59:47,39.34,Mobile Payment,Chicago,5
4,NaN,1.000000e+09,2020-12-10 00:59:59,NaN,Debit Card,Houston,6
...,...,...,...,...,...,...,...
499995,499996.0,1.000500e+09,2020-09-24 22:14:19,55.76,Mobile Payment,Los Angeles,499997
499996,499997.0,1.000500e+09,2020-02-20 14:19:47,98.90,Debit Card,Houston,499998
499997,499998.0,1.000500e+09,2021-09-18 00:46:54,16.58,Debit Card,San Francisco,499999
499998,499999.0,1.000500e+09,2022-10-17 07:23:27,60.74,Cash,Seattle,500000
499999,500000.0,1.000500e+09,2024-03-27 23:39:07,40.34,Mobile Payment,New York,500001

## 9. Handling Missing Data

**Definitions:**
- *Missing Values:* Empty or NaN entries.

**Methods:**
- `isnull()`
- `dropna()`
- `fillna()`
- `interpolate()`

In [130]:
df.isnull().sum()

user_id         1
order_id        1
order_date      0
order_amount    2
payment_mode    1
city            2
new_data        0
dtype: int64

In [131]:
df.dropna(axis=1, inplace=True)
df

                 order_date  new_data
0       2022-01-21 06:27:29         2
1       2023-03-01 13:01:21         3
2       2024-03-21 15:37:04         4
3       2020-10-31 09:59:47         5
4       2020-12-10 00:59:59         6
...                     ...       ...
499995  2020-09-24 22:14:19    499997
499996  2020-02-20 14:19:47    499998
499997  2021-09-18 00:46:54    499999
499998  2022-10-17 07:23:27    500000
499999  2024-03-27 23:39:07    500001

[500000 rows x 2 columns]

In [132]:
df.fillna(40, inplace=True)
df

                 order_date  new_data
0       2022-01-21 06:27:29         2
1       2023-03-01 13:01:21         3
2       2024-03-21 15:37:04         4
3       2020-10-31 09:59:47         5
4       2020-12-10 00:59:59         6
...                     ...       ...
499995  2020-09-24 22:14:19    499997
499996  2020-02-20 14:19:47    499998
499997  2021-09-18 00:46:54    499999
499998  2022-10-17 07:23:27    500000
499999  2024-03-27 23:39:07    500001

[500000 rows x 2 columns]

## 10. Interpolation

**What:** Fill missing values using trends.

**Types:** linear, polynomial, time.

In [133]:
df = pd.read_csv('raw_data.csv')
df.interpolate(method='linear', axis=0, inplace=True)
df

/tmp/ipykernel_13768/101066057.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='linear', axis=0, inplace=True)

,user_id,order_id,order_date,order_amount,payment_mode,city
0,1.0,1.000000e+09,2022-01-21 06:27:29,71.65,NaN,Los Angeles
1,2.0,1.000000e+09,2023-03-01 13:01:21,56.57,Cash,NaN
2,3.0,1.000000e+09,2024-03-21 15:37:04,41.49,NaN,Houston
3,4.0,1.000000e+09,2020-10-31 09:59:47,39.34,Mobile Payment,Chicago
4,5.0,1.000000e+09,2020-12-10 00:59:59,55.79,Debit Card,Houston
...,...,...,...,...,...,...
499995,499996.0,1.000500e+09,2020-09-24 22:14:19,55.76,Mobile Payment,Los Angeles
499996,499997.0,1.000500e+09,2020-02-20 14:19:47,98.90,Debit Card,Houston
499997,499998.0,1.000500e+09,2021-09-18 00:46:54,16.58,Debit Card,San Francisco
499998,499999.0,1.000500e+09,2022-10-17 07:23:27,60.74,Cash,Seattle
499999,500000.0,1.000500e+09,2024-03-27 23:39:07,40.34,Mobile Payment,New York

## 11. Sorting Data

**What:** Arrange rows by column values.

In [134]:
df.sort_values(by=['order_date','order_amount'], ascending=[True,True], inplace=True)
df

,user_id,order_id,order_date,order_amount,payment_mode,city
79694,79695.0,1.000080e+09,2020-01-01 00:14:06,44.81,Credit Card,Houston
96508,96509.0,1.000097e+09,2020-01-01 00:17:28,58.22,Cash,Houston
69785,69786.0,1.000070e+09,2020-01-01 00:20:46,99.31,Credit Card,Seattle
35739,35740.0,1.000036e+09,2020-01-01 00:24:00,5.02,Credit Card,Boston
193082,193083.0,1.000193e+09,2020-01-01 00:24:20,23.32,Debit Card,Chicago
...,...,...,...,...,...,...
298374,298375.0,1.000298e+09,2024-05-18 19:23:19,93.32,Mobile Payment,Boston
442620,442621.0,1.000443e+09,2024-05-18 19:28:08,86.27,Mobile Payment,Boston
446202,446203.0,1.000446e+09,2024-05-18 19:29:12,5.06,Mobile Payment,Dallas
8443,8444.0,1.000008e+09,2024-05-18 19:29:37,6.22,Mobile Payment,Atlanta
407647,407648.0,1.000408e+09,2024-05-18 19:31:03,41.57,Credit Card,Chicago

## 12. Aggregation

**What:** Compute statistics.

**Examples:** min, max, mean, std, sum, count.

In [135]:
print(df['order_amount'].min())
print(df['order_amount'].max())
print(df['order_amount'].mean())
print(df['order_amount'].std())
print(df['order_amount'].sum())
print(df['order_amount'].count())

5.0
100.0
52.46533444
27.409630251366526
26232667.22
500000

## 13. Grouping Data

**What:** Group rows and apply functions.

In [136]:
df.groupby('payment_mode')['order_amount'].sum()

payment_mode
Cash              6588862.44
Credit Card       6577608.11
Debit Card        6529306.45
Mobile Payment    6536777.08
Name: order_amount, dtype: float64

## 14. Merging DataFrames

**What:** Combine DataFrames.

**How:** Use `pd.merge()`.

**Types:** left, right, inner, outer, cross.

In [137]:
merged_df = pd.merge(df, df, on='user_id', how='right')
merged_df

,user_id,order_id_x,order_date_x,order_amount_x,payment_mode_x,city_x,order_id_y,order_date_y,order_amount_y,payment_mode_y,city_y
0,79695.0,1.000080e+09,2020-01-01 00:14:06,44.81,Credit Card,Houston,1.000080e+09,2020-01-01 00:14:06,44.81,Credit Card,Houston
1,96509.0,1.000097e+09,2020-01-01 00:17:28,58.22,Cash,Houston,1.000097e+09,2020-01-01 00:17:28,58.22,Cash,Houston
2,69786.0,1.000070e+09,2020-01-01 00:20:46,99.31,Credit Card,Seattle,1.000070e+09,2020-01-01 00:20:46,99.31,Credit Card,Seattle
3,35740.0,1.000036e+09,2020-01-01 00:24:00,5.02,Credit Card,Boston,1.000036e+09,2020-01-01 00:24:00,5.02,Credit Card,Boston
4,193083.0,1.000193e+09,2020-01-01 00:24:20,23.32,Debit Card,Chicago,1.000193e+09,2020-01-01 00:24:20,23.32,Debit Card,Chicago
...,...,...,...,...,...,...,...,...,...,...,...
499995,298375.0,1.000298e+09,2024-05-18 19:23:19,93.32,Mobile Payment,Boston,1.000298e+09,2024-05-18 19:23:19,93.32,Mobile Payment,Boston
499996,442621.0,1.000443e+09,2024-05-18 19:28:08,86.27,Mobile Payment,Boston,1.000443e+09,2024-05-18 19:28:08,86.27,Mobile Payment,Boston
499997,446203.0,1.000446e+09,2024-05-18 19:29:12,5.06,Mobile Payment,Dallas,1.000446e+09,2024-05-18 19:29:12,5.06,Mobile Payment,Dallas
499998,8444.0,1.000008e+09,2024-05-18 19:29:37,6.22,Mobile Payment,Atlanta,1.000008e+09,2024-05-18 19:29:37,6.22,Mobile Payment,Atlanta
499999,407648.0,1.000408e+09,2024-05-18 19:31:03,41.57,Credit Card,Chicago,1.000408e+09,2024-05-18 19:31:03,41.57,Credit Card,Chicago

## 15. Concatenation

**What:** Stack DataFrames.

**How:** Use `pd.concat()`.

In [138]:
# Example
# pd.concat([df1, df2], axis=0, ignore_index=True)

---

**End of Pandas Practice Notebook**